/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __GENERATED_GPIODBUS_H__
#define __GENERATED_GPIODBUS_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for io.gpiod1.Chip */

#define GPIODBUS_TYPE_CHIP (gpiodbus_chip_get_type ())
#define GPIODBUS_CHIP(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPIODBUS_TYPE_CHIP, GpiodbusChip))
#define GPIODBUS_IS_CHIP(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPIODBUS_TYPE_CHIP))
#define GPIODBUS_CHIP_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), GPIODBUS_TYPE_CHIP, GpiodbusChipIface))

struct _GpiodbusChip;
typedef struct _GpiodbusChip GpiodbusChip;
typedef struct _GpiodbusChipIface GpiodbusChipIface;

struct _GpiodbusChipIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_request_lines) (
    GpiodbusChip *object,
    GDBusMethodInvocation *invocation,
    GVariant *arg_line_config,
    GVariant *arg_request_config);

  const gchar * (*get_label) (GpiodbusChip *object);

  const gchar * (*get_name) (GpiodbusChip *object);

  guint  (*get_num_lines) (GpiodbusChip *object);

  const gchar * (*get_path) (GpiodbusChip *object);

};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GpiodbusChip, g_object_unref)
#endif

GType gpiodbus_chip_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *gpiodbus_chip_interface_info (void);
guint gpiodbus_chip_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void gpiodbus_chip_complete_request_lines (
    GpiodbusChip *object,
    GDBusMethodInvocation *invocation,
    const gchar *request_path);



/* D-Bus method calls: */
void gpiodbus_chip_call_request_lines (
    GpiodbusChip *proxy,
    GVariant *arg_line_config,
    GVariant *arg_request_config,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean gpiodbus_chip_call_request_lines_finish (
    GpiodbusChip *proxy,
    gchar **out_request_path,
    GAsyncResult *res,
    GError **error);

gboolean gpiodbus_chip_call_request_lines_sync (
    GpiodbusChip *proxy,
    GVariant *arg_line_config,
    GVariant *arg_request_config,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    gchar **out_request_path,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
const gchar *gpiodbus_chip_get_name (GpiodbusChip *object);
gchar *gpiodbus_chip_dup_name (GpiodbusChip *object);
void gpiodbus_chip_set_name (GpiodbusChip *object, const gchar *value);

const gchar *gpiodbus_chip_get_label (GpiodbusChip *object);
gchar *gpiodbus_chip_dup_label (GpiodbusChip *object);
void gpiodbus_chip_set_label (GpiodbusChip *object, const gchar *value);

guint gpiodbus_chip_get_num_lines (GpiodbusChip *object);
void gpiodbus_chip_set_num_lines (GpiodbusChip *object, guint value);

const gchar *gpiodbus_chip_get_path (GpiodbusChip *object);
gchar *gpiodbus_chip_dup_path (GpiodbusChip *object);
void gpiodbus_chip_set_path (GpiodbusChip *object, const gchar *value);


/* ---- */

#define GPIODBUS_TYPE_CHIP_PROXY (gpiodbus_chip_proxy_get_type ())
#define GPIODBUS_CHIP_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPIODBUS_TYPE_CHIP_PROXY, GpiodbusChipProxy))
#define GPIODBUS_CHIP_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), GPIODBUS_TYPE_CHIP_PROXY, GpiodbusChipProxyClass))
#define GPIODBUS_CHIP_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPIODBUS_TYPE_CHIP_PROXY, GpiodbusChipProxyClass))
#define GPIODBUS_IS_CHIP_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPIODBUS_TYPE_CHIP_PROXY))
#define GPIODBUS_IS_CHIP_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPIODBUS_TYPE_CHIP_PROXY))

typedef struct _GpiodbusChipProxy GpiodbusChipProxy;
typedef struct _GpiodbusChipProxyClass GpiodbusChipProxyClass;
typedef struct _GpiodbusChipProxyPrivate GpiodbusChipProxyPrivate;

struct _GpiodbusChipProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  GpiodbusChipProxyPrivate *priv;
};

struct _GpiodbusChipProxyClass
{
  GDBusProxyClass parent_class;
};

GType gpiodbus_chip_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GpiodbusChipProxy, g_object_unref)
#endif

void gpiodbus_chip_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
GpiodbusChip *gpiodbus_chip_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
GpiodbusChip *gpiodbus_chip_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void gpiodbus_chip_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
GpiodbusChip *gpiodbus_chip_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
GpiodbusChip *gpiodbus_chip_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define GPIODBUS_TYPE_CHIP_SKELETON (gpiodbus_chip_skeleton_get_type ())
#define GPIODBUS_CHIP_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPIODBUS_TYPE_CHIP_SKELETON, GpiodbusChipSkeleton))
#define GPIODBUS_CHIP_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), GPIODBUS_TYPE_CHIP_SKELETON, GpiodbusChipSkeletonClass))
#define GPIODBUS_CHIP_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPIODBUS_TYPE_CHIP_SKELETON, GpiodbusChipSkeletonClass))
#define GPIODBUS_IS_CHIP_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPIODBUS_TYPE_CHIP_SKELETON))
#define GPIODBUS_IS_CHIP_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPIODBUS_TYPE_CHIP_SKELETON))

typedef struct _GpiodbusChipSkeleton GpiodbusChipSkeleton;
typedef struct _GpiodbusChipSkeletonClass GpiodbusChipSkeletonClass;
typedef struct _GpiodbusChipSkeletonPrivate GpiodbusChipSkeletonPrivate;

struct _GpiodbusChipSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  GpiodbusChipSkeletonPrivate *priv;
};

struct _GpiodbusChipSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType gpiodbus_chip_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GpiodbusChipSkeleton, g_object_unref)
#endif

GpiodbusChip *gpiodbus_chip_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for io.gpiod1.Line */

#define GPIODBUS_TYPE_LINE (gpiodbus_line_get_type ())
#define GPIODBUS_LINE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPIODBUS_TYPE_LINE, GpiodbusLine))
#define GPIODBUS_IS_LINE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPIODBUS_TYPE_LINE))
#define GPIODBUS_LINE_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), GPIODBUS_TYPE_LINE, GpiodbusLineIface))

struct _GpiodbusLine;
typedef struct _GpiodbusLine GpiodbusLine;
typedef struct _GpiodbusLineIface GpiodbusLineIface;

struct _GpiodbusLineIface
{
  GTypeInterface parent_iface;


  gboolean  (*get_active_low) (GpiodbusLine *object);

  const gchar * (*get_bias) (GpiodbusLine *object);

  const gchar * (*get_consumer) (GpiodbusLine *object);

  guint64  (*get_debounce_period_us) (GpiodbusLine *object);

  gboolean  (*get_debounced) (GpiodbusLine *object);

  const gchar * (*get_direction) (GpiodbusLine *object);

  const gchar * (*get_drive) (GpiodbusLine *object);

  const gchar * (*get_edge_detection) (GpiodbusLine *object);

  const gchar * (*get_event_clock) (GpiodbusLine *object);

  gboolean  (*get_managed) (GpiodbusLine *object);

  const gchar * (*get_name) (GpiodbusLine *object);

  guint  (*get_offset) (GpiodbusLine *object);

  const gchar * (*get_request_path) (GpiodbusLine *object);

  gboolean  (*get_used) (GpiodbusLine *object);

  void (*edge_event) (
    GpiodbusLine *object,
    GVariant *arg_event_data);

};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GpiodbusLine, g_object_unref)
#endif

GType gpiodbus_line_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *gpiodbus_line_interface_info (void);
guint gpiodbus_line_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus signal emissions functions: */
void gpiodbus_line_emit_edge_event (
    GpiodbusLine *object,
    GVariant *arg_event_data);



/* D-Bus property accessors: */
guint gpiodbus_line_get_offset (GpiodbusLine *object);
void gpiodbus_line_set_offset (GpiodbusLine *object, guint value);

const gchar *gpiodbus_line_get_name (GpiodbusLine *object);
gchar *gpiodbus_line_dup_name (GpiodbusLine *object);
void gpiodbus_line_set_name (GpiodbusLine *object, const gchar *value);

gboolean gpiodbus_line_get_used (GpiodbusLine *object);
void gpiodbus_line_set_used (GpiodbusLine *object, gboolean value);

const gchar *gpiodbus_line_get_consumer (GpiodbusLine *object);
gchar *gpiodbus_line_dup_consumer (GpiodbusLine *object);
void gpiodbus_line_set_consumer (GpiodbusLine *object, const gchar *value);

const gchar *gpiodbus_line_get_direction (GpiodbusLine *object);
gchar *gpiodbus_line_dup_direction (GpiodbusLine *object);
void gpiodbus_line_set_direction (GpiodbusLine *object, const gchar *value);

const gchar *gpiodbus_line_get_edge_detection (GpiodbusLine *object);
gchar *gpiodbus_line_dup_edge_detection (GpiodbusLine *object);
void gpiodbus_line_set_edge_detection (GpiodbusLine *object, const gchar *value);

const gchar *gpiodbus_line_get_bias (GpiodbusLine *object);
gchar *gpiodbus_line_dup_bias (GpiodbusLine *object);
void gpiodbus_line_set_bias (GpiodbusLine *object, const gchar *value);

const gchar *gpiodbus_line_get_drive (GpiodbusLine *object);
gchar *gpiodbus_line_dup_drive (GpiodbusLine *object);
void gpiodbus_line_set_drive (GpiodbusLine *object, const gchar *value);

gboolean gpiodbus_line_get_active_low (GpiodbusLine *object);
void gpiodbus_line_set_active_low (GpiodbusLine *object, gboolean value);

gboolean gpiodbus_line_get_debounced (GpiodbusLine *object);
void gpiodbus_line_set_debounced (GpiodbusLine *object, gboolean value);

guint64 gpiodbus_line_get_debounce_period_us (GpiodbusLine *object);
void gpiodbus_line_set_debounce_period_us (GpiodbusLine *object, guint64 value);

const gchar *gpiodbus_line_get_event_clock (GpiodbusLine *object);
gchar *gpiodbus_line_dup_event_clock (GpiodbusLine *object);
void gpiodbus_line_set_event_clock (GpiodbusLine *object, const gchar *value);

gboolean gpiodbus_line_get_managed (GpiodbusLine *object);
void gpiodbus_line_set_managed (GpiodbusLine *object, gboolean value);

const gchar *gpiodbus_line_get_request_path (GpiodbusLine *object);
gchar *gpiodbus_line_dup_request_path (GpiodbusLine *object);
void gpiodbus_line_set_request_path (GpiodbusLine *object, const gchar *value);


/* ---- */

#define GPIODBUS_TYPE_LINE_PROXY (gpiodbus_line_proxy_get_type ())
#define GPIODBUS_LINE_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPIODBUS_TYPE_LINE_PROXY, GpiodbusLineProxy))
#define GPIODBUS_LINE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), GPIODBUS_TYPE_LINE_PROXY, GpiodbusLineProxyClass))
#define GPIODBUS_LINE_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPIODBUS_TYPE_LINE_PROXY, GpiodbusLineProxyClass))
#define GPIODBUS_IS_LINE_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPIODBUS_TYPE_LINE_PROXY))
#define GPIODBUS_IS_LINE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPIODBUS_TYPE_LINE_PROXY))

typedef struct _GpiodbusLineProxy GpiodbusLineProxy;
typedef struct _GpiodbusLineProxyClass GpiodbusLineProxyClass;
typedef struct _GpiodbusLineProxyPrivate GpiodbusLineProxyPrivate;

struct _GpiodbusLineProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  GpiodbusLineProxyPrivate *priv;
};

struct _GpiodbusLineProxyClass
{
  GDBusProxyClass parent_class;
};

GType gpiodbus_line_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GpiodbusLineProxy, g_object_unref)
#endif

void gpiodbus_line_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
GpiodbusLine *gpiodbus_line_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
GpiodbusLine *gpiodbus_line_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void gpiodbus_line_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
GpiodbusLine *gpiodbus_line_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
GpiodbusLine *gpiodbus_line_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define GPIODBUS_TYPE_LINE_SKELETON (gpiodbus_line_skeleton_get_type ())
#define GPIODBUS_LINE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPIODBUS_TYPE_LINE_SKELETON, GpiodbusLineSkeleton))
#define GPIODBUS_LINE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), GPIODBUS_TYPE_LINE_SKELETON, GpiodbusLineSkeletonClass))
#define GPIODBUS_LINE_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPIODBUS_TYPE_LINE_SKELETON, GpiodbusLineSkeletonClass))
#define GPIODBUS_IS_LINE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPIODBUS_TYPE_LINE_SKELETON))
#define GPIODBUS_IS_LINE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPIODBUS_TYPE_LINE_SKELETON))

typedef struct _GpiodbusLineSkeleton GpiodbusLineSkeleton;
typedef struct _GpiodbusLineSkeletonClass GpiodbusLineSkeletonClass;
typedef struct _GpiodbusLineSkeletonPrivate GpiodbusLineSkeletonPrivate;

struct _GpiodbusLineSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  GpiodbusLineSkeletonPrivate *priv;
};

struct _GpiodbusLineSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType gpiodbus_line_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GpiodbusLineSkeleton, g_object_unref)
#endif

GpiodbusLine *gpiodbus_line_skeleton_new (void);


/* ------------------------------------------------------------------------ */
/* Declarations for io.gpiod1.Request */

#define GPIODBUS_TYPE_REQUEST (gpiodbus_request_get_type ())
#define GPIODBUS_REQUEST(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPIODBUS_TYPE_REQUEST, GpiodbusRequest))
#define GPIODBUS_IS_REQUEST(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPIODBUS_TYPE_REQUEST))
#define GPIODBUS_REQUEST_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), GPIODBUS_TYPE_REQUEST, GpiodbusRequestIface))

struct _GpiodbusRequest;
typedef struct _GpiodbusRequest GpiodbusRequest;
typedef struct _GpiodbusRequestIface GpiodbusRequestIface;

struct _GpiodbusRequestIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_get_values) (
    GpiodbusRequest *object,
    GDBusMethodInvocation *invocation,
    GVariant *arg_offsets);

  gboolean (*handle_reconfigure_lines) (
    GpiodbusRequest *object,
    GDBusMethodInvocation *invocation,
    GVariant *arg_line_config);

  gboolean (*handle_release) (
    GpiodbusRequest *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_set_values) (
    GpiodbusRequest *object,
    GDBusMethodInvocation *invocation,
    GVariant *arg_values);

  const gchar * (*get_chip_path) (GpiodbusRequest *object);

  const gchar *const * (*get_line_paths) (GpiodbusRequest *object);

};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GpiodbusRequest, g_object_unref)
#endif

GType gpiodbus_request_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *gpiodbus_request_interface_info (void);
guint gpiodbus_request_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void gpiodbus_request_complete_release (
    GpiodbusRequest *object,
    GDBusMethodInvocation *invocation);

void gpiodbus_request_complete_reconfigure_lines (
    GpiodbusRequest *object,
    GDBusMethodInvocation *invocation);

void gpiodbus_request_complete_get_values (
    GpiodbusRequest *object,
    GDBusMethodInvocation *invocation,
    GVariant *values);

void gpiodbus_request_complete_set_values (
    GpiodbusRequest *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void gpiodbus_request_call_release (
    GpiodbusRequest *proxy,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean gpiodbus_request_call_release_finish (
    GpiodbusRequest *proxy,
    GAsyncResult *res,
    GError **error);

gboolean gpiodbus_request_call_release_sync (
    GpiodbusRequest *proxy,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);

void gpiodbus_request_call_reconfigure_lines (
    GpiodbusRequest *proxy,
    GVariant *arg_line_config,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean gpiodbus_request_call_reconfigure_lines_finish (
    GpiodbusRequest *proxy,
    GAsyncResult *res,
    GError **error);

gboolean gpiodbus_request_call_reconfigure_lines_sync (
    GpiodbusRequest *proxy,
    GVariant *arg_line_config,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);

void gpiodbus_request_call_get_values (
    GpiodbusRequest *proxy,
    GVariant *arg_offsets,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean gpiodbus_request_call_get_values_finish (
    GpiodbusRequest *proxy,
    GVariant **out_values,
    GAsyncResult *res,
    GError **error);

gboolean gpiodbus_request_call_get_values_sync (
    GpiodbusRequest *proxy,
    GVariant *arg_offsets,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GVariant **out_values,
    GCancellable *cancellable,
    GError **error);

void gpiodbus_request_call_set_values (
    GpiodbusRequest *proxy,
    GVariant *arg_values,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean gpiodbus_request_call_set_values_finish (
    GpiodbusRequest *proxy,
    GAsyncResult *res,
    GError **error);

gboolean gpiodbus_request_call_set_values_sync (
    GpiodbusRequest *proxy,
    GVariant *arg_values,
    GDBusCallFlags call_flags,
    gint timeout_msec,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
const gchar *gpiodbus_request_get_chip_path (GpiodbusRequest *object);
gchar *gpiodbus_request_dup_chip_path (GpiodbusRequest *object);
void gpiodbus_request_set_chip_path (GpiodbusRequest *object, const gchar *value);

const gchar *const *gpiodbus_request_get_line_paths (GpiodbusRequest *object);
gchar **gpiodbus_request_dup_line_paths (GpiodbusRequest *object);
void gpiodbus_request_set_line_paths (GpiodbusRequest *object, const gchar *const *value);


/* ---- */

#define GPIODBUS_TYPE_REQUEST_PROXY (gpiodbus_request_proxy_get_type ())
#define GPIODBUS_REQUEST_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPIODBUS_TYPE_REQUEST_PROXY, GpiodbusRequestProxy))
#define GPIODBUS_REQUEST_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), GPIODBUS_TYPE_REQUEST_PROXY, GpiodbusRequestProxyClass))
#define GPIODBUS_REQUEST_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPIODBUS_TYPE_REQUEST_PROXY, GpiodbusRequestProxyClass))
#define GPIODBUS_IS_REQUEST_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPIODBUS_TYPE_REQUEST_PROXY))
#define GPIODBUS_IS_REQUEST_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPIODBUS_TYPE_REQUEST_PROXY))

typedef struct _GpiodbusRequestProxy GpiodbusRequestProxy;
typedef struct _GpiodbusRequestProxyClass GpiodbusRequestProxyClass;
typedef struct _GpiodbusRequestProxyPrivate GpiodbusRequestProxyPrivate;

struct _GpiodbusRequestProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  GpiodbusRequestProxyPrivate *priv;
};

struct _GpiodbusRequestProxyClass
{
  GDBusProxyClass parent_class;
};

GType gpiodbus_request_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GpiodbusRequestProxy, g_object_unref)
#endif

void gpiodbus_request_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
GpiodbusRequest *gpiodbus_request_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
GpiodbusRequest *gpiodbus_request_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void gpiodbus_request_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
GpiodbusRequest *gpiodbus_request_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
GpiodbusRequest *gpiodbus_request_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define GPIODBUS_TYPE_REQUEST_SKELETON (gpiodbus_request_skeleton_get_type ())
#define GPIODBUS_REQUEST_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPIODBUS_TYPE_REQUEST_SKELETON, GpiodbusRequestSkeleton))
#define GPIODBUS_REQUEST_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), GPIODBUS_TYPE_REQUEST_SKELETON, GpiodbusRequestSkeletonClass))
#define GPIODBUS_REQUEST_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPIODBUS_TYPE_REQUEST_SKELETON, GpiodbusRequestSkeletonClass))
#define GPIODBUS_IS_REQUEST_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPIODBUS_TYPE_REQUEST_SKELETON))
#define GPIODBUS_IS_REQUEST_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPIODBUS_TYPE_REQUEST_SKELETON))

typedef struct _GpiodbusRequestSkeleton GpiodbusRequestSkeleton;
typedef struct _GpiodbusRequestSkeletonClass GpiodbusRequestSkeletonClass;
typedef struct _GpiodbusRequestSkeletonPrivate GpiodbusRequestSkeletonPrivate;

struct _GpiodbusRequestSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  GpiodbusRequestSkeletonPrivate *priv;
};

struct _GpiodbusRequestSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType gpiodbus_request_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GpiodbusRequestSkeleton, g_object_unref)
#endif

GpiodbusRequest *gpiodbus_request_skeleton_new (void);


/* ---- */

#define GPIODBUS_TYPE_OBJECT (gpiodbus_object_get_type ())
#define GPIODBUS_OBJECT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPIODBUS_TYPE_OBJECT, GpiodbusObject))
#define GPIODBUS_IS_OBJECT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPIODBUS_TYPE_OBJECT))
#define GPIODBUS_OBJECT_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), GPIODBUS_TYPE_OBJECT, GpiodbusObject))

struct _GpiodbusObject;
typedef struct _GpiodbusObject GpiodbusObject;
typedef struct _GpiodbusObjectIface GpiodbusObjectIface;

struct _GpiodbusObjectIface
{
  GTypeInterface parent_iface;
};

GType gpiodbus_object_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GpiodbusObject, g_object_unref)
#endif

GpiodbusChip *gpiodbus_object_get_chip (GpiodbusObject *object);
GpiodbusLine *gpiodbus_object_get_line (GpiodbusObject *object);
GpiodbusRequest *gpiodbus_object_get_request (GpiodbusObject *object);
GpiodbusChip *gpiodbus_object_peek_chip (GpiodbusObject *object);
GpiodbusLine *gpiodbus_object_peek_line (GpiodbusObject *object);
GpiodbusRequest *gpiodbus_object_peek_request (GpiodbusObject *object);

#define GPIODBUS_TYPE_OBJECT_PROXY (gpiodbus_object_proxy_get_type ())
#define GPIODBUS_OBJECT_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPIODBUS_TYPE_OBJECT_PROXY, GpiodbusObjectProxy))
#define GPIODBUS_OBJECT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), GPIODBUS_TYPE_OBJECT_PROXY, GpiodbusObjectProxyClass))
#define GPIODBUS_OBJECT_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPIODBUS_TYPE_OBJECT_PROXY, GpiodbusObjectProxyClass))
#define GPIODBUS_IS_OBJECT_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPIODBUS_TYPE_OBJECT_PROXY))
#define GPIODBUS_IS_OBJECT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPIODBUS_TYPE_OBJECT_PROXY))

typedef struct _GpiodbusObjectProxy GpiodbusObjectProxy;
typedef struct _GpiodbusObjectProxyClass GpiodbusObjectProxyClass;
typedef struct _GpiodbusObjectProxyPrivate GpiodbusObjectProxyPrivate;

struct _GpiodbusObjectProxy
{
  /*< private >*/
  GDBusObjectProxy parent_instance;
  GpiodbusObjectProxyPrivate *priv;
};

struct _GpiodbusObjectProxyClass
{
  GDBusObjectProxyClass parent_class;
};

GType gpiodbus_object_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GpiodbusObjectProxy, g_object_unref)
#endif

GpiodbusObjectProxy *gpiodbus_object_proxy_new (GDBusConnection *connection, const gchar *object_path);

#define GPIODBUS_TYPE_OBJECT_SKELETON (gpiodbus_object_skeleton_get_type ())
#define GPIODBUS_OBJECT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPIODBUS_TYPE_OBJECT_SKELETON, GpiodbusObjectSkeleton))
#define GPIODBUS_OBJECT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), GPIODBUS_TYPE_OBJECT_SKELETON, GpiodbusObjectSkeletonClass))
#define GPIODBUS_OBJECT_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPIODBUS_TYPE_OBJECT_SKELETON, GpiodbusObjectSkeletonClass))
#define GPIODBUS_IS_OBJECT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPIODBUS_TYPE_OBJECT_SKELETON))
#define GPIODBUS_IS_OBJECT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPIODBUS_TYPE_OBJECT_SKELETON))

typedef struct _GpiodbusObjectSkeleton GpiodbusObjectSkeleton;
typedef struct _GpiodbusObjectSkeletonClass GpiodbusObjectSkeletonClass;
typedef struct _GpiodbusObjectSkeletonPrivate GpiodbusObjectSkeletonPrivate;

struct _GpiodbusObjectSkeleton
{
  /*< private >*/
  GDBusObjectSkeleton parent_instance;
  GpiodbusObjectSkeletonPrivate *priv;
};

struct _GpiodbusObjectSkeletonClass
{
  GDBusObjectSkeletonClass parent_class;
};

GType gpiodbus_object_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GpiodbusObjectSkeleton, g_object_unref)
#endif

GpiodbusObjectSkeleton *gpiodbus_object_skeleton_new (const gchar *object_path);
void gpiodbus_object_skeleton_set_chip (GpiodbusObjectSkeleton *object, GpiodbusChip *interface_);
void gpiodbus_object_skeleton_set_line (GpiodbusObjectSkeleton *object, GpiodbusLine *interface_);
void gpiodbus_object_skeleton_set_request (GpiodbusObjectSkeleton *object, GpiodbusRequest *interface_);

/* ---- */

#define GPIODBUS_TYPE_OBJECT_MANAGER_CLIENT (gpiodbus_object_manager_client_get_type ())
#define GPIODBUS_OBJECT_MANAGER_CLIENT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GPIODBUS_TYPE_OBJECT_MANAGER_CLIENT, GpiodbusObjectManagerClient))
#define GPIODBUS_OBJECT_MANAGER_CLIENT_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), GPIODBUS_TYPE_OBJECT_MANAGER_CLIENT, GpiodbusObjectManagerClientClass))
#define GPIODBUS_OBJECT_MANAGER_CLIENT_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GPIODBUS_TYPE_OBJECT_MANAGER_CLIENT, GpiodbusObjectManagerClientClass))
#define GPIODBUS_IS_OBJECT_MANAGER_CLIENT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GPIODBUS_TYPE_OBJECT_MANAGER_CLIENT))
#define GPIODBUS_IS_OBJECT_MANAGER_CLIENT_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GPIODBUS_TYPE_OBJECT_MANAGER_CLIENT))

typedef struct _GpiodbusObjectManagerClient GpiodbusObjectManagerClient;
typedef struct _GpiodbusObjectManagerClientClass GpiodbusObjectManagerClientClass;
typedef struct _GpiodbusObjectManagerClientPrivate GpiodbusObjectManagerClientPrivate;

struct _GpiodbusObjectManagerClient
{
  /*< private >*/
  GDBusObjectManagerClient parent_instance;
  GpiodbusObjectManagerClientPrivate *priv;
};

struct _GpiodbusObjectManagerClientClass
{
  GDBusObjectManagerClientClass parent_class;
};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GpiodbusObjectManagerClient, g_object_unref)
#endif

GType gpiodbus_object_manager_client_get_type (void) G_GNUC_CONST;

GType gpiodbus_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager, const gchar *object_path, const gchar *interface_name, gpointer user_data);

void gpiodbus_object_manager_client_new (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data);
GDBusObjectManager *gpiodbus_object_manager_client_new_finish (
    GAsyncResult        *res,
    GError             **error);
GDBusObjectManager *gpiodbus_object_manager_client_new_sync (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error);

void gpiodbus_object_manager_client_new_for_bus (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data);
GDBusObjectManager *gpiodbus_object_manager_client_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
GDBusObjectManager *gpiodbus_object_manager_client_new_for_bus_sync (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error);


G_END_DECLS

#endif /* __GENERATED_GPIODBUS_H__ */
